/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package studentscores;

/**
 *
 * @author Amy
 */
public class GUI extends javax.swing.JFrame {

	/**
	 * Creates new form GUI
	 */
	public GUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        StudentsInClassLabel = new javax.swing.JLabel();
        NumStudentsField = new javax.swing.JTextField();
        NumStudentsOKButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        CurrentStudentDataLabel = new javax.swing.JLabel();
        LNameField = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        GradesLabel = new javax.swing.JLabel();
        Grade1Field = new javax.swing.JTextField();
        Grade2Field = new javax.swing.JTextField();
        Grade3Field = new javax.swing.JTextField();
        NextStudentButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        StudentDataTitleLabel = new javax.swing.JLabel();
        ClassAverageDataLabel = new javax.swing.JLabel();
        QuitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTextBox = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        ClassAverageLabel = new javax.swing.JLabel();
        AsLabel = new javax.swing.JLabel();
        BsLabel = new javax.swing.JLabel();
        CsLabel = new javax.swing.JLabel();
        DsLabel = new javax.swing.JLabel();
        FsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StudentsInClassLabel.setText("How many students are in the class?");

        NumStudentsField.setText(" ");
        NumStudentsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumStudentsFieldActionPerformed(evt);
            }
        });
        NumStudentsField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NumStudentsFieldFocusGained(evt);
            }
        });

        NumStudentsOKButton.setText("OK");
        NumStudentsOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumStudentsOKButtonActionPerformed(evt);
            }
        });

        CurrentStudentDataLabel.setText("Enter the current student's information:");

        LNameField.setText("Last Name");
        LNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameFieldActionPerformed(evt);
            }
        });
        LNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LNameFieldFocusGained(evt);
            }
        });

        NameLabel.setText("Name:");

        GradesLabel.setText("Grades:");

        Grade1Field.setColumns(5);
        Grade1Field.setText(" Grade 1");
        Grade1Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Grade1FieldFocusGained(evt);
            }
        });

        Grade2Field.setColumns(5);
        Grade2Field.setText(" Grade 2");
        Grade2Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Grade2FieldFocusGained(evt);
            }
        });

        Grade3Field.setColumns(5);
        Grade3Field.setText(" Grade 3");
        Grade3Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Grade3FieldFocusGained(evt);
            }
        });

        NextStudentButton.setText("Next Student");
        NextStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextStudentButtonActionPerformed(evt);
            }
        });

        StudentDataTitleLabel.setText("Student Data");

        ClassAverageDataLabel.setText("Class Averages");

        QuitButton.setText("Quit");
        QuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButtonActionPerformed(evt);
            }
        });

        StudentTextBox.setColumns(20);
        StudentTextBox.setRows(5);
        jScrollPane1.setViewportView(StudentTextBox);

        jLabel1.setText("Name - Average - Grade");

        ClassAverageLabel.setText("Average:");

        AsLabel.setText("As: ");

        BsLabel.setText("Bs:");

        CsLabel.setText("Cs:");

        DsLabel.setText("Ds:");

        FsLabel.setText("Fs:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(LNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(GradesLabel)
                                .addGap(18, 18, 18)
                                .addComponent(Grade1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(Grade2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(Grade3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CurrentStudentDataLabel))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StudentsInClassLabel)
                        .addGap(45, 45, 45)
                        .addComponent(NumStudentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(NumStudentsOKButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QuitButton)
                        .addGap(23, 23, 23))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(StudentDataTitleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(NextStudentButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClassAverageDataLabel)
                            .addComponent(ClassAverageLabel)
                            .addComponent(AsLabel)
                            .addComponent(BsLabel)
                            .addComponent(CsLabel)
                            .addComponent(DsLabel)
                            .addComponent(FsLabel))
                        .addGap(180, 180, 180)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentsInClassLabel)
                    .addComponent(NumStudentsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumStudentsOKButton)
                    .addComponent(QuitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CurrentStudentDataLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel)
                    .addComponent(GradesLabel)
                    .addComponent(Grade1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grade2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grade3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NextStudentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentDataTitleLabel)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ClassAverageDataLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ClassAverageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FsLabel)))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void LNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameFieldActionPerformed
      // lock edits on the output field
		StudentTextBox.setEditable(false);
   }//GEN-LAST:event_LNameFieldActionPerformed

   private void LNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LNameFieldFocusGained
      LNameField.selectAll();
   }//GEN-LAST:event_LNameFieldFocusGained

   private void Grade1FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Grade1FieldFocusGained
      Grade1Field.selectAll();
   }//GEN-LAST:event_Grade1FieldFocusGained

   private void Grade2FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Grade2FieldFocusGained
      Grade2Field.selectAll();
   }//GEN-LAST:event_Grade2FieldFocusGained

   private void Grade3FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Grade3FieldFocusGained
      Grade3Field.selectAll();
   }//GEN-LAST:event_Grade3FieldFocusGained

   private void NextStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextStudentButtonActionPerformed

      /* Retrieve data from fields, store into object in array, output object's data,
      * and also handle class average and grade curve.
      */
		
      //reset score
      score = 0.0;

      //create student object to hold this student at the right point in the array
      allStudents[StudentsEntered] = new Student();

      //store student's last name
      allStudents[StudentsEntered].setName(LNameField.getText());

      //get student scores and sum them
      score = Double.parseDouble(Grade1Field.getText()) + Double.parseDouble(Grade2Field.getText())
      + Double.parseDouble(Grade3Field.getText());

      //pass score to Student class for averaging and determining grade
      allStudents[StudentsEntered].calcAvg(score, numtests);

      //output data from current student to Student Data section of GUI
		StudentTextBox.append(allStudents[StudentsEntered].print2());
		
		//class average and grade curve
		//track the number of students with each grade
		switch(allStudents[StudentsEntered].getGrade())
		{
			case 'A':
				numAs++;
				break;
			case 'B':
				numBs++;
				break;
			case 'C':
				numCs++;
				break;
			case 'D':
				numDs++;
				break;
			case 'F':
				numFs++;
				break;
			default:
				System.out.println("Something went wrong, your student doesn't have a grade.");
				break;
		}
		
		//track running total of all grades
		runningtotal = runningtotal + allStudents[StudentsEntered].getAvg();
		
		//increment StudentsEntered counter
      StudentsEntered++;
		
		ClassAverageLabel.setText("Average: " + ((float)Math.round(((runningtotal / StudentsEntered) * 100) / 100)));
		AsLabel.setText("As: " + numAs);
		BsLabel.setText("Bs: " + numBs);
		CsLabel.setText("Cs: " + numCs);
		DsLabel.setText("Ds: " + numDs);
		FsLabel.setText("Fs: " + numFs);
   }//GEN-LAST:event_NextStudentButtonActionPerformed

   private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButtonActionPerformed
      System.exit(0);
   }//GEN-LAST:event_QuitButtonActionPerformed

   private void NumStudentsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumStudentsFieldActionPerformed
      // misclick; no code
   }//GEN-LAST:event_NumStudentsFieldActionPerformed

   private void NumStudentsOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumStudentsOKButtonActionPerformed
      
		// save number of students from text field to variable for reuse
		numstudents = Integer.parseInt(NumStudentsField.getText());
		
		// create array of students that will hold the entire class
		allStudents = new Student[numstudents];
		
		// lock NumStudentsField to prevent further user input
		NumStudentsField.setEditable(false);
		
   }//GEN-LAST:event_NumStudentsOKButtonActionPerformed

   private void NumStudentsFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumStudentsFieldFocusGained
      NumStudentsField.selectAll();
   }//GEN-LAST:event_NumStudentsFieldFocusGained

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI().setVisible(true);
			}
		});
	}
	
	// my variable declarations - initialize everything to except numtests
	int numstudents = 0, StudentsEntered = 0, numAs = 0, numBs = 0, numCs = 0, numDs = 0, numFs = 0;
	double score = 0.0, runningtotal = 0.0;
	Student allStudents[];
	final int numtests = 3;
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AsLabel;
    private javax.swing.JLabel BsLabel;
    private javax.swing.JLabel ClassAverageDataLabel;
    private javax.swing.JLabel ClassAverageLabel;
    private javax.swing.JLabel CsLabel;
    private javax.swing.JLabel CurrentStudentDataLabel;
    private javax.swing.JLabel DsLabel;
    private javax.swing.JLabel FsLabel;
    private javax.swing.JTextField Grade1Field;
    private javax.swing.JTextField Grade2Field;
    private javax.swing.JTextField Grade3Field;
    private javax.swing.JLabel GradesLabel;
    private javax.swing.JTextField LNameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton NextStudentButton;
    private javax.swing.JTextField NumStudentsField;
    private javax.swing.JButton NumStudentsOKButton;
    private javax.swing.JButton QuitButton;
    private javax.swing.JLabel StudentDataTitleLabel;
    private javax.swing.JTextArea StudentTextBox;
    private javax.swing.JLabel StudentsInClassLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
